#!/bin/bash

# Source: https://medium.com/swlh/compiling-rust-for-raspberry-pi-arm-922b55dbb050

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly HOSTNAME=ad102-rpi-cm4-1
readonly HOSTUSER=ad102

readonly TARGET_HOST=${HOSTUSER}@${HOSTNAME}
readonly TARGET_PATH=/home/${HOSTUSER}/controller
readonly TARGET_ARCH=aarch64-unknown-linux-gnu
readonly SOURCE_PATH=./target/${TARGET_ARCH}/debug/controller

cargo build --target $TARGET_ARCH
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}
